### ISSUE TITLE
Add `cairocffi` as a dependency

### ISSUE THREAD

**Issue by tresoldi** [jboynyc/textnets#14]
* Textnets version: 0.4.9
* Python version: 3.7
* Operating System: Linux

### Description

In most environments created afresh, no engine for rendering the Cairo output will be available, which means the the examples from the tutorial will not run out-of-the-box.

Also considering how Cairo can be difficult to install in some cases, I suggest adding `cairocffi` as a dependency or, at least, clearly stating the alternatives. 

### What I Did

```
pip install cairocffi
```

**Comment by jboynyc** [comment]
`pycairo` is now included as a dependency to make use of plotting features easier (0e8af66). I updated the installation docs to reflect this, and to direct users for whom the pycairo dependency does not work to install `cairoffi` using pip or conda (8e07647). I'd appreciate your feedback on whether that is clear/helpful, @tresoldi.

I will merge this into trunk and create a new release soon.

I agree that creating a Conda package (#15) would probably still be the easiest way to get Windows users on board.

**Edit:** Apologies, I just understood that you suggested requiring *a drop-in replacement* for pycairo. I will test that option now.

**Comment by tresoldi** [comment]
This is great, thanks! As for the suggestion, it is mostly in order to follow the journal instructions that users should be able to follow the docs to get the results that are demonstrated. A drop-in replacement for pycairo can be taken as a suggestion, but not as a request, I'm happy with these instructions.

As for Conda, it is also a suggestion, but approving the manuscript absolutely does not depend on that. In fact, I suppose all is done, once you release and make a note in the JOSS issue I'm happy to give my ok. :)

**Comment by jboynyc** [comment]
Thanks! I did make the change to cairocffi because it looks less painful as a cross-platform dependency (5adba03a3831fc74cf58db372a26d370a925cbcc, ddc5b0fdb175203ab927b540cbb6c465727e1166).
