### ISSUE TITLE
[Commands for running Tests]

### ISSUE THREAD

**Issue by sara-02** [jboynyc/textnets#17]
* Textnets version: 0.4.10
* Python version: 3.8
* Operating System: Ubuntu

### Description
What are the commands to run tests for textnet once I have forked the repository?
I could not find that in either the docs or the Readme.md.

Can we add a line about that?

**Comment by jboynyc** [comment]
This is in the [contribution docs](https://textnets.readthedocs.io/en/stable/contributing.html) but I can make it more visible. Where would you suggest adding this?

**Comment by sara-02** [comment]
Hey @jboynyc my bad I did not see the 5th point.
I was able to use it to run the tests.

**Comment by sara-02** [comment]
But my test-all command is failing for py 3.8, should I create another issue for it?

**Comment by sara-02** [comment]
> This is in the [contribution docs](https://textnets.readthedocs.io/en/stable/contributing.html) but I can make it more visible. Where would you suggest adding this?

I think this works, we can also list `pytest, black` along with `flask8 and tox` before running tests.

**Comment by jboynyc** [comment]
> But my test-all command is failing for py 3.8, should I create another issue for it?

Oh strange, the tests run fine [on Travis](https://travis-ci.org/github/jboynyc/textnets). So yes, please do file a separate issue with details I can investigate.

**Comment by jboynyc** [comment]
> I think this works, we can also list `pytest, black` along with `flask8 and tox` before running tests.

The makefile runs `black` an `flake8` when `make lint` is invoked.

**Comment by sara-02** [comment]
> > I think this works, we can also list `pytest, black` along with `flask8 and tox` before running tests.
> 
> The makefile runs `black` an `flake8` when `make lint` is invoked.

Oh got it.
