### ISSUE TITLE
implement more measures to aid interpretation

### ISSUE THREAD

**Issue by jboynyc** [jboynyc/textnets#23]
For instance [Liebig & Rao (2014)](https://arxiv.org/abs/1406.5814) to identify influential nodes driving clustering.

**Comment by jboynyc** [comment]
@BrandonKMLee given your apparent detailed knowledge of the Python ecosystem for network analysis, do you know of any project that implements a clustering coefficient for bipartite networks (or anything comparable)? 

(Same question about #24, where I'm collecting ideas for improved backbone extraction of projected networks. I've come across the `backbone` package for R which implements a few techniques, but nothing comparable in Python land.)

**Comment by BradKML** [comment]
Firstly, obligatory reference to Centrality https://github.com/jboynyc/textnets/issues/32

Also for Bipartite-specific Metrics, which most are based on HITS or PageRank:
- https://arxiv.org/pdf/0710.0117.pdf
- https://osf.io/preprints/socarxiv/hazvs/download
- https://sci-hub.se/10.1016/j.physa.2008.09.006
- https://sci-hub.se/10.1080/00222500590889730
- https://joss.theoj.org/papers/10.21105/joss.02315.pdf
- https://cs.paperswithcode.com/paper/hellrank-a-hellinger-based-centrality-measure
- https://doi.org/10.1017/dsj.2017.32

Also for NetwrokX, the basic centralities (includes redundancy) and Clustering data exists
- https://networkx.org/documentation/stable/reference/algorithms/bipartite.html#module-networkx.algorithms.bipartite.cluster
- https://networkx.org/documentation/stable/reference/algorithms/bipartite.html#module-networkx.algorithms.bipartite.centrality
- https://networkx.org/documentation/stable/reference/algorithms/bipartite.html#module-networkx.algorithms.bipartite.redundancy

**Comment by jboynyc** [comment]
Closing for now, as the new release will include bipartite centrality measures and a clustering coefficient. Will likely revisit this in the future.
