### ISSUE TITLE
Add max_words argument for Textnet class 

### ISSUE THREAD

**Issue by jboynyc** [jboynyc/textnets#25]
Right now `Textnet` takes a `min_docs` argument. As an alternative, it could accept a `max_words` argument, in which case only the specified number of terms would be included in the textnet (because of a limited attention space, for instance).

**Comment by Atsaniik** [comment]
That is great, but is possible also add one more argument(drop out the docs). If it does not have the terms that would make the tn.plot more readable. 

in1: `tn = Textnet(corpus.tokenized(), min_docs=10)`
out1:`Textnet(109 docs, 96 terms, 1691 edges)`

in2: `tn = Textnet(corpus.tokenized(), min_docs=20)`
out2:`Textnet(109 docs, 24 terms, 720 edges)`

Thanks

**Comment by jboynyc** [comment]
Hi @pengKiina, how about if it were possible to pass `connected=True` when initializing a `Textnet` to ensure that only the connected component is kept?

**Comment by jboynyc** [comment]
Upon reflection, max_words doesn't really make sense, since it isn't immediately obvious which terms should be kept. As for the other request in this issue, it will be handled in an upcoming release through the inclusion of a connected keyword option.
