### ISSUE TITLE
Idea to consider: Stylometry and Readability

### ISSUE THREAD

**Issue by BradKML** [jboynyc/textnets#34]
Scattertext is another repo that is worth checking out https://github.com/JasonKessler/scattertext

Stylometric Repos exists for identifying the mood and/or authorship of an item
- https://github.com/jpotts18/stylometry
- https://github.com/mikekestemont/pystyl
- https://github.com/worldwise001/stylometry
- https://github.com/pagea/unstyle
- https://github.com/rakshithShetty/A4NT-author-masking

Also with a readability as a possible variable to control (if there are casual documents):
- https://github.com/shivam5992/textstat
- https://github.com/retextjs/retext-readability
- https://github.com/words/automated-readability#related

**Comment by jboynyc** [comment]
Thanks, I'm aware of scattertext and like the project.

The other resources are out of scope for this project.

**Comment by BradKML** [comment]
Understood the non-need for anonymous author attribution.
