### ISSUE TITLE
How do I add a background box（bbox） to a node label?

### ISSUE THREAD

**Issue by clark874** [jboynyc/textnets#47]
First of all, as a sociology scholar like you, I sincerely appreciate your work! 

In my use of textnets, I have found the node label to be a headache: its display is many times not clear. I would like to be able to add a background box for the node labels, so that the font can be displayed more clearly. However, I have tried various methods to achieve this feature. In contrast, the ability to add a label background box in networkx is very easy to implement. 

If you know how to add it, please let me know, thank you!

**Comment by jboynyc** [comment]
Thanks for submitting your question! I don't know of any way to add a background to labels, though I agree it would be a nice feature, so I'll look into what it would take to add that option.

In the meantime, the easiest thing would probably be to [save the graph](https://textnets.readthedocs.io/en/stable/_api/textnets.network.Textnet.html#textnets.network.Textnet.save_graph) and load in in NetworkX to do the visualization you envision.

**Comment by jboynyc** [comment]
I've asked for some pointers for where to start implementing this [in the igraph support forum](https://igraph.discourse.group/t/draw-vertex-labels-with-a-background/1291).

**Comment by clark874** [comment]
> 

Thank you. I've tried to export the graph to NetworkX but the process is not as convenient as textnets since there is no text network processing package for NetworkX. I also found that igraph's graph procedure is not as easy-doing as NetworkX, which has a very detailed document to follow. I think it would be a good idea to integrate more local python graph packages in textnets than relaying solely on igraph from R.

**Comment by jboynyc** [comment]
That's a misunderstanding. I am not relying on the R interface to igraph, but the [Python interface](https://igraph.org/python/). It isn't as easy to work with as networkx, but it is much more powerful. I also try to take some of the pain out of it by adding a wrapper over the plotting functionality.

I am trying not to add dependencies on additional libraries, but I could add more information about working with networkx to the documentation (something I currently do a bit of under [Advanced Topics](https://textnets.readthedocs.io/en/stable/advanced.html)).

**Comment by clark874** [comment]
> That's a misunderstanding. I am not relying on the R interface to igraph, but the [Python interface](https://igraph.org/python/). It isn't as easy to work with as networkx, but it is much more powerful. I also try to take some of the pain out of it by adding a wrapper over the plotting functionality.
> 
> I am trying not to add dependencies on additional libraries, but I could add more information about working with networkx to the documentation (something I currently do a bit of under [Advanced Topics](https://textnets.readthedocs.io/en/stable/advanced.html)).

Thank you for your reply. I will try learning igraph by studying Tutorial. Besides, your case study of using textnets to analyze political texts from your blog is also very helpful. It would be great to see more such kinds of practical case studies! Also if there are any published papers of textnets, I would wait no time to cite them in my research!

**Comment by jboynyc** [comment]
> Also if there are any published papers of textnets, I would wait no time to cite them in my research!

Soon, I hope. Writing and publishing moves much more slowly than software development...

**Comment by jboynyc** [comment]
Closing this for now, as it is quite messy to do with the Cairo plotting backend. Maybe as `matplotlib` becomes the norm in `igraph`, I can revisit this.
