### ISSUE TITLE
g.es["cost"] = [1 / pow(w, tn.params["tuning_parameter"]) for w in g.es["weight"]]

### ISSUE THREAD

**Issue by segu239** [jboynyc/textnets#59]
File "C:\Users\Telemetria\AppData\Local\Programs\Python\Python311\Lib\site-packages\textnets\network.py", line 835, in _graph_from_im
    g.es["cost"] = [1 / pow(w, tn.params["tuning_parameter"]) for w in g.es["weight"]]

**Comment by jboynyc** [comment]
What is the bug exactly?

**Comment by segu239** [comment]
Sorry, I put the label wrong, it's a help request

**Comment by jboynyc** [comment]
The tuning parameter defaults to 0.5, in accordance with Opsahl, Agneessens, Skvoretz, [Node centrality in weighted networks: generalizing degree and shortest paths](https://doi.org/10.1016/j.socnet.2010.03.006). If you want to set a different tuning parameter, you can assign your desired value to `tn.params["tuning_parameter"]`.
