### ISSUE TITLE
Stopwords and formatiing

### ISSUE THREAD

**Issue by cacostame** [jboynyc/textnets#60]
Hi John. Thank you for developing this application. it is very interesting. I have two questions for which I could not find information in the tutorial.
1. Is there a way that I can add an additional stopword?
2. Is there a way to modify the size of the nodes and/or the text font size?
Thanks again for your help.

**Comment by jboynyc** [comment]
1.  Yes, you can pass a list of additional stopwords to `tokenized`, `ngrams` or `noun_phrases`. See the docs [here](https://textnets.readthedocs.io/en/stable/_api/textnets.corpus.Corpus.html) (search for "remove").

2. When calling the `plot` method, you can pass `node_label_size` to set the font size. The size of the nodes can be fixed using `node_size`, or you can pass `scale_nodes_by` with the name of a centrality measure to scale nodes by centrality.

Hope that helps!

**Comment by cacostame** [comment]
thank you John! i really appreciate it
