### ISSUE TITLE
Installation failure using pip

### ISSUE THREAD

**Issue by aswansyahputra** [jboynyc/textnets#61]
**Describe the bug**
Can't install using `pip install textnets` command.

**To Reproduce**
- `pip install textnets` (under conda virtual env)

**Expected behavior**
textnets can successfully installed into device.

**Platform (please complete the following information):**
 - OS: macOS aarch64-apple-darwin20
 - Python version 3.12.0
 - How did you install the package? pip
 - Which version of `textnets` are you using? Have you tried updating to the latest release? textnets v0.93..

**Additional context**
<img width="1216" alt="image" src="https://github.com/jboynyc/textnets/assets/12567035/b42c9bf9-7ffb-4481-ba4a-c60bb456e54c">

**Comment by jboynyc** [comment]
Judging by the output in your screenshot, `pip` for some reason tried to install version 0.4.11, which is very old. Not sure why that would happen. I hope to publish a new release next week; hopefully that will solve this issue.
