### ISSUE TITLE
Build warning: "" 

### ISSUE THREAD

**Issue by sarahec** [jboynyc/textnets#63]
**Describe the bug**
Cython 3 (as required) wants a `language_level` setting to determine Python compatibility.

**Expected behavior**
Cython should know which language level to use. See `language_level` under [compiler directives](https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#compiler-directives). 

**Platform (please complete the following information):**
 - OS: [e.g. Windows, Mac, Linux] Linux (NixOS)
 - Python version [e.g. 3.8] 3.11.7
 - How did you install the package? [e.g. conda, pip] Was building 0.9.4 for the nixpkgs repo.
 - Which version of `textnets` are you using? Have you tried updating to the latest release? 0.9.4

**Comment by jboynyc** [comment]
Thanks, I'll make a new release with this fix asap.

**Comment by jboynyc** [comment]
Fixed in c44c8ae182f299b564866515e13eb3ecfb68dcb5, part of v0.9.5.
